// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Dengcy",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Dengcy",
            targets: ["AppModule"],
            bundleIdentifier: "com.LZC.Dengcy1",
            teamIdentifier: "ZWN93323N2",
            displayVersion: "1.1",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            capabilities: [
                .camera(purposeString: "We need camera access for hand pose detection")
            ],
            appCategory: .games
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)